//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hatoca.lu.se", ConfigurationName="ServiceReference.CSharpWebServiceSoap")]
    public interface CSharpWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name filename from namespace http://hatoca.lu.se is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hatoca.lu.se/GetFileContent", ReplyAction="*")]
        BookingApp.ServiceReference.GetFileContentResponse GetFileContent(BookingApp.ServiceReference.GetFileContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hatoca.lu.se/GetFileContent", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingApp.ServiceReference.GetFileContentResponse> GetFileContentAsync(BookingApp.ServiceReference.GetFileContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContent", Namespace="http://hatoca.lu.se", Order=0)]
        public BookingApp.ServiceReference.GetFileContentRequestBody Body;
        
        public GetFileContentRequest() {
        }
        
        public GetFileContentRequest(BookingApp.ServiceReference.GetFileContentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hatoca.lu.se")]
    public partial class GetFileContentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetFileContentRequestBody() {
        }
        
        public GetFileContentRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContentResponse", Namespace="http://hatoca.lu.se", Order=0)]
        public BookingApp.ServiceReference.GetFileContentResponseBody Body;
        
        public GetFileContentResponse() {
        }
        
        public GetFileContentResponse(BookingApp.ServiceReference.GetFileContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hatoca.lu.se")]
    public partial class GetFileContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileContentResult;
        
        public GetFileContentResponseBody() {
        }
        
        public GetFileContentResponseBody(string GetFileContentResult) {
            this.GetFileContentResult = GetFileContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CSharpWebServiceSoapChannel : BookingApp.ServiceReference.CSharpWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSharpWebServiceSoapClient : System.ServiceModel.ClientBase<BookingApp.ServiceReference.CSharpWebServiceSoap>, BookingApp.ServiceReference.CSharpWebServiceSoap {
        
        public CSharpWebServiceSoapClient() {
        }
        
        public CSharpWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSharpWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSharpWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSharpWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingApp.ServiceReference.GetFileContentResponse BookingApp.ServiceReference.CSharpWebServiceSoap.GetFileContent(BookingApp.ServiceReference.GetFileContentRequest request) {
            return base.Channel.GetFileContent(request);
        }
        
        public string GetFileContent(string filename) {
            BookingApp.ServiceReference.GetFileContentRequest inValue = new BookingApp.ServiceReference.GetFileContentRequest();
            inValue.Body = new BookingApp.ServiceReference.GetFileContentRequestBody();
            inValue.Body.filename = filename;
            BookingApp.ServiceReference.GetFileContentResponse retVal = ((BookingApp.ServiceReference.CSharpWebServiceSoap)(this)).GetFileContent(inValue);
            return retVal.Body.GetFileContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingApp.ServiceReference.GetFileContentResponse> BookingApp.ServiceReference.CSharpWebServiceSoap.GetFileContentAsync(BookingApp.ServiceReference.GetFileContentRequest request) {
            return base.Channel.GetFileContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingApp.ServiceReference.GetFileContentResponse> GetFileContentAsync(string filename) {
            BookingApp.ServiceReference.GetFileContentRequest inValue = new BookingApp.ServiceReference.GetFileContentRequest();
            inValue.Body = new BookingApp.ServiceReference.GetFileContentRequestBody();
            inValue.Body.filename = filename;
            return ((BookingApp.ServiceReference.CSharpWebServiceSoap)(this)).GetFileContentAsync(inValue);
        }
    }
}
