//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.WebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hatoca.lu.se", ConfigurationName="WebServiceRef.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name filename from namespace http://hatoca.lu.se is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://hatoca.lu.se/GetFileContent", ReplyAction="*")]
        Booking.WebServiceRef.GetFileContentResponse GetFileContent(Booking.WebServiceRef.GetFileContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hatoca.lu.se/GetFileContent", ReplyAction="*")]
        System.Threading.Tasks.Task<Booking.WebServiceRef.GetFileContentResponse> GetFileContentAsync(Booking.WebServiceRef.GetFileContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContent", Namespace="http://hatoca.lu.se", Order=0)]
        public Booking.WebServiceRef.GetFileContentRequestBody Body;
        
        public GetFileContentRequest() {
        }
        
        public GetFileContentRequest(Booking.WebServiceRef.GetFileContentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hatoca.lu.se")]
    public partial class GetFileContentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public GetFileContentRequestBody() {
        }
        
        public GetFileContentRequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileContentResponse", Namespace="http://hatoca.lu.se", Order=0)]
        public Booking.WebServiceRef.GetFileContentResponseBody Body;
        
        public GetFileContentResponse() {
        }
        
        public GetFileContentResponse(Booking.WebServiceRef.GetFileContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hatoca.lu.se")]
    public partial class GetFileContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileContentResult;
        
        public GetFileContentResponseBody() {
        }
        
        public GetFileContentResponseBody(string GetFileContentResult) {
            this.GetFileContentResult = GetFileContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Booking.WebServiceRef.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Booking.WebServiceRef.WebServiceSoap>, Booking.WebServiceRef.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Booking.WebServiceRef.GetFileContentResponse Booking.WebServiceRef.WebServiceSoap.GetFileContent(Booking.WebServiceRef.GetFileContentRequest request) {
            return base.Channel.GetFileContent(request);
        }
        
        public string GetFileContent(string filename) {
            Booking.WebServiceRef.GetFileContentRequest inValue = new Booking.WebServiceRef.GetFileContentRequest();
            inValue.Body = new Booking.WebServiceRef.GetFileContentRequestBody();
            inValue.Body.filename = filename;
            Booking.WebServiceRef.GetFileContentResponse retVal = ((Booking.WebServiceRef.WebServiceSoap)(this)).GetFileContent(inValue);
            return retVal.Body.GetFileContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Booking.WebServiceRef.GetFileContentResponse> Booking.WebServiceRef.WebServiceSoap.GetFileContentAsync(Booking.WebServiceRef.GetFileContentRequest request) {
            return base.Channel.GetFileContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Booking.WebServiceRef.GetFileContentResponse> GetFileContentAsync(string filename) {
            Booking.WebServiceRef.GetFileContentRequest inValue = new Booking.WebServiceRef.GetFileContentRequest();
            inValue.Body = new Booking.WebServiceRef.GetFileContentRequestBody();
            inValue.Body.filename = filename;
            return ((Booking.WebServiceRef.WebServiceSoap)(this)).GetFileContentAsync(inValue);
        }
    }
}
